### ISSUE TITLE
Sprint 3 | Shipment 

### ISSUE THREAD

**Issue by prabhleen-kaur-hub** [TransparentPath/buildly-react-template#17]
Shipment is the second screen after dashboard. The screen has the following elements: 

1. Add shipment: This will allow the user to add the shipment.
2. Search bar: This will allow a user to search the shipment. It has two filters i.e sort by and alerts.
    2.1. Sort by: Most recent/Least recent/Highest Values/ Lowest Values/ Custodian A-Z/ Custodian Z-A
    2.2. Alerts: All/Recall/Temperature/Humidity/Last Shipment
3. Refresh Data: TBD
4. Map

User will be able to Add/Edit/Delete the shipment 

**Stories Associated:** 

- [x] 1. Empty Board: https://github.com/TransparentPath/buildly-react-template/issues/8
- [x] 2. Add shipment: 
  - [x]  2.1 Shipment details: https://github.com/TransparentPath/buildly-react-template/issues/9\
  - [x] 2.2 Add item: https://github.com/TransparentPath/buildly-react-template/issues/11
  - [x] 2.3 Add Custodians: https://github.com/TransparentPath/buildly-react-template/issues/1 
  - [x] 2.4 Sensor and Gateway: https://github.com/TransparentPath/buildly-react-template/issues/12
  - [x] 2.5 Shipment overview: https://github.com/TransparentPath/buildly-react-template/issues/13
- [x] 3. Edit/Delete: https://github.com/TransparentPath/buildly-react-template/issues/14

**Comment by prabhleen-kaur-hub** [comment]
Feedback: July 8, 2020
Shipments View

- [ ] In 'Add Shipments' view, swap 'Scheduled Arrival' with Scheduled Departure'.
- [ ] I like the ability to change time using military style but would be good to include the ability to change minutes next to hours to minimize issues.
- [ ] For 'Mode Type' or other similar drop down it would be good to list the most commonly or recently used items at the top.
- [ ] For Excursions/Warnings - there's no ability to choose multiple,
- [ ] Can only save but couldn't go to 'Next : Add Items' unless select edit on Shipment view.
- [ ] Difference between 'Alerts' on Shipment view and 'Excursions/Warnings' in 'Add Shipments'
