### ISSUE TITLE
Find latency with Tive date FE (1hr delay)

### ISSUE THREAD

**Issue by karrla** [TransparentPath/buildly-react-template#283]
**Issue**
Frontend - There is a current 1hr delay from when the Tive gateway is turned to when we capture any data.

see BE issue too

**Tasks**

- [ ]  Between Tive and Transparent Path BE - Cron time interval
- [ ]  Between BE and FE - Solutions can be Websocket , Polling
- [ ]  Capture and display data as soon as Tive Gateway/Sensor is turned on

 **Reference**

https://trello.com/c/8jRUtyW9/109-capture-initial-data-from-tive

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Capture initial data from Tive](https://trello.com/c/8jRUtyW9/109-capture-initial-data-from-tive)

**Comment by yasmin2496** [comment]
Applies to https://github.com/TransparentPath/sensor_service/issues/163
@karrla There was a conversation happening few months back on this issue. We came up with a solution to have all Tive gateways timed to send data back at constant time interval (example: 15 mins) so then we can use the Cron job to fetch data for the same time interval.

Currently since each Tive gateway has its own interval parameter this problem is happening for syncing data from Tive back to Transparent Path

For FE side of the ticket websockets is something we can pick up and do it once the Tive to Transparent Path problem is resolved

We can't really capture the data the moment Tive gateway is turned on. This comes back to the interval set for the gateway. But if they strongly insist we might have to update the cron job interval to 2 mins or such but this will severly degrade the performance.

**Comment by yasmin2496** [comment]
@karrla @glind Any updates on the above pointers?
