### ISSUE TITLE
UX Enhancement for Shipment Table

### ISSUE THREAD

**Issue by karrla** [TransparentPath/buildly-react-template#288]
**Description**

The team would like some updates to improve the UX of the Shipment Table.

See referenced [screenshot ](https://drive.google.com/file/d/1coTmtcrnXDcgcpRWVmeHzLbzEClYojS2/view?usp=sharing)

**Tasks**
- [x] Move "Add Shipment" button to the top right of the table, on the same line as the "Shipments" page title 
- [x] Change the default layout be stacked, with shipment table first, then map in the middle, and sensor table at the bottom  
- [x] Place all of the icons (search, download, print, columns, filter, change view) all on the same line, preferably on the same line as the active/completed/canceled tabs, to better use the vertical screen space
- [x] Change the column headers to match[ the screenshot:](https://drive.google.com/file/d/1coTmtcrnXDcgcpRWVmeHzLbzEClYojS2/view?usp=sharing) VIEW, SHIPMENT NAME, DEPART, ARRIVE, SENSOR, STATUS, ALERTS?
- [x] Remove radio button from each row item 
- [x] Change "Select the row" by clicking anywhere in the row (instead of the current radio select button) 
- [x] Change the selected row highlight color to match the selected left tab color instead
- [x] Remove the column and icons for Delete. See [already ticketed issue](https://github.com/TransparentPath/buildly-react-template/issues/284)
- [x] Increase the SHIPMENT NAME column width to **minimize text wrapping**
- [x] For DEPART and ARRIVE columns, **remove timestamp** and abbreviate months to the first three letters to optimize space and prevent line wrapping

**Comment by karrla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UX Enhancements: Shipments Table](https://trello.com/c/JzyKCtkT/61-ux-enhancements-shipments-table)

**Comment by SiddharthBhansali13** [comment]
The enhancement is completed (minus 1 task), PR #298 raised.

**Comment by yasmin2496** [comment]
![image](https://user-images.githubusercontent.com/61192422/156379922-83ce18d0-a90d-409a-b246-aa621e0bd28a.png)
Final changes on the Shipment page @glind @karrla
