### ISSUE TITLE
Final changes to stabilize the build v0.5.6

### ISSUE THREAD

**Issue by yasmin2496** [TransparentPath/buildly-react-template#349]
### Task list

- [ ] New workflow only the gateways that start with G are showing up on the platform.
- [ ] It looks like the new workflow was included in this release and it shouldn't have been since there are still some issues that exist and probably won't have time to resolve them quickly. Is it possible to roll back to the previous working workflow?
- [ ] Alerts seem to be working except I only see one pop alert at a time in the app. unless I refresh and then see the next pop up alert, then refresh again to see the next alert, etc. - see video below. I don't know if anything can be done about this?
- [ ] Is it possible on the 'Shipments' view / map, to remove the message 'Please wait for new reports to aggregate' since the performance issue is no longer there - see image below.
- [ ] In the 'Reports' view, can the 'Active' and 'Completed' shipments in the drop down be listed with the most recent shipment at the top rather than at the bottom?
