### ISSUE TITLE
Tracker UI and other issues

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#500]
- [x] Make email across platform case insensitive.
- [x] When deselecting any environment variables in create shipment, do not display the maximum and minimum values in the graph in reporting section.
- [x] Change UI for info window in map component for mobile screens.
- [x] Change PDF download option so that a user can generate report again if anything changes or download the report if its already generated and don't have to generate every time he/she visits the same shipment reporting section.
- [x] Change Trackers page to list the trackers based on shippers. Also display device inventory for each shipper. Also added power column to indicate which devices are on and off, certificate of collaboration column, and added visual indicator for device status.
