### ISSUE TITLE
Tracker Changes

### ISSUE THREAD

**Issue by TanmayJain92** [TransparentPath/buildly-react-template#503]
- [x] Exclude user names from translating.
- [x] Update power column UI for better differentiation and update Inventory UI for displaying only devices that are present only.
- [x] Add multiple select functionality for devices and provide options for edit status, edit shipper and remove tracker.
- [x] Add tracker sync option.
- [x] Add tracker section in Admin Panel which will display new devices and reused devices. Both type of devices can be uploaded from there. Only for Global Admin.
- [x] Make shipment estimated departure time red if it is delayed and show its alert.
